In [67]:
import numpy as np
import matplotlib.pyplot as plt
import string
from sklearn.model_selection import train_test_split

In [68]:
archivos = [
    "benedetti.txt",
    "neruda.txt"
]

In [69]:
texts = []
labels = []

In [70]:
for label, l in enumerate(archivos):
    print(f"{l} Corresponde a {label}")
    
    with open(l, "r", encoding="utf-8") as archivo:
        for line in archivo: #recorrer cada una de las lineas de los textos con line
            #print(line)
            line = line.rstrip().lower() #todo a minuscula
            #print(line)
            if line:
                #eliminar puntuacion
                line = line.translate(str.maketrans("", "", string.punctuation))
                texts.append(line)
                labels.append(label)
            print(line)
            

benedetti.txt Corresponde a 0
poemas varios
mario benedetti

la buena tiniebla
una mujer desnuda y en lo oscuro
genera un resplandor que da confianza
de modo que si sobreviene
un apagón o un desconsuelo
es conveniente y hasta imprescindible
tener a mano una mujer desnuda
entonces las paredes se acuarelan
el cielo raso se convierte en cielo
las telarañas vibran en su ángulo
los almanaques dominguean
y los ojos felices y felinos
miran y no se cansan de mirar
una mujer desnuda y en lo oscuro
una mujer querida o a querer
exorcisa por una vez la muerte

preliminar del miedo
por sobre las terrazas alunadas
donde se aman cautelosamente los gatos
y los brillos esquivan las chimeneas
creo que nadie sabe lo que yo sé esta noche
algo aprendido a pedacitos y a pulsaciones
y que integra mi pánico tradicional modesto
¿cómo desmenuzar plácidamente el miedo
comprender por fin que no es una excusa
sino un escalofrío parecido al disfrute
sólo que amarguísimo y si atenuantes
los suicidas no tienen proble

In [71]:
texts

['poemas varios',
 'mario benedetti',
 'la buena tiniebla',
 'una mujer desnuda y en lo oscuro',
 'genera un resplandor que da confianza',
 'de modo que si sobreviene',
 'un apagón o un desconsuelo',
 'es conveniente y hasta imprescindible',
 'tener a mano una mujer desnuda',
 'entonces las paredes se acuarelan',
 'el cielo raso se convierte en cielo',
 'las telarañas vibran en su ángulo',
 'los almanaques dominguean',
 'y los ojos felices y felinos',
 'miran y no se cansan de mirar',
 'una mujer desnuda y en lo oscuro',
 'una mujer querida o a querer',
 'exorcisa por una vez la muerte',
 'preliminar del miedo',
 'por sobre las terrazas alunadas',
 'donde se aman cautelosamente los gatos',
 'y los brillos esquivan las chimeneas',
 'creo que nadie sabe lo que yo sé esta noche',
 'algo aprendido a pedacitos y a pulsaciones',
 'y que integra mi pánico tradicional modesto',
 '¿cómo desmenuzar plácidamente el miedo',
 'comprender por fin que no es una excusa',
 'sino un escalofrío parecido 

In [72]:
print(labels)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [73]:
train_text, test_text, Ytrain, Ytest = train_test_split(texts, labels, test_size=0.1, random_state=42)

In [74]:
len(Ytrain), len(Ytest)

(3526, 392)

In [75]:
test_text

['o no tener',
 'en ti se acumularon las guerras y los vuelos',
 'por colores',
 'combatido en la puerta del viento del verano',
 'usted no sabe cómo yo valoro',
 'para venir a preguntarnos',
 'mis trayectos contigo',
 'los cuadros',
 'pobres y malheridas',
 'poema 10',
 'que no nos sirve ahora',
 'oh la cópula loca de esperanza y esfuerzo',
 'le dio refugio y café instantáneos',
 'desperdiciando la avenida',
 'no dejes caer lo párpados',
 'xxi',
 'entre qué genes',
 'culpable o inocente',
 'miran y no se cansan de mirar',
 'me defienden de la pálida',
 'claro que la soledad no viene sola',
 'mientras almorzaban por primera vez',
 'ovíllate a mi lado como si tuvieras miedo',
 'copulan y duermen',
 'ah silenciosa',
 'de la ajada miseria y de los miserables',
 'o que yo pueda o creerme que puedo',
 'huracanes de sueños aún a veces las tumban',
 'una palabra entonces una sonrisa bastan',
 'girante errante noche la cavadora de ojos',
 'veinte poemas de amor',
 'en la infancia de niebla mi 

In [76]:
#<unk> es una convencion que se utiliza a menudo en NLP para representar
#palabras desconocidas o fuera del vocabulario. En este caso, se esta
#asignando el indice 0 a esta palabra especial
indice = 1
indice_palabras = {"<unk>": 0}

In [77]:
#construccion deun diccionario de codificacion de palabras a indices
#recorrer el conjunto de entranmiento # a cada linea se le asigna una tokenizacion, es decir separar en palabras las lineas
#y a cada palabra se le asigna un indice
for text in train_text:  
    tokens = text.split()  
    for token in tokens: 
        if token not in indice_palabras:
            indice_palabras[token] = indice  
            indice += 1

In [78]:
indice_palabras

{'<unk>': 0,
 'claro': 1,
 'que': 2,
 'la': 3,
 'soledad': 4,
 'no': 5,
 'viene': 6,
 'sola': 7,
 'oscuros': 8,
 'cauces': 9,
 'donde': 10,
 'sed': 11,
 'eterna': 12,
 'sigue': 13,
 'catorce': 14,
 'disfrutar': 15,
 'mientras': 16,
 'se': 17,
 'pueda': 18,
 'ah': 19,
 'mujer': 20,
 'sé': 21,
 'cómo': 22,
 'pudiste': 23,
 'contenerme': 24,
 'otoño': 25,
 'siento': 26,
 'viajar': 27,
 'tus': 28,
 'ojos': 29,
 'y': 30,
 'es': 31,
 'distante': 32,
 'el': 33,
 'en': 34,
 'red': 35,
 'de': 36,
 'mi': 37,
 'música': 38,
 'estás': 39,
 'presa': 40,
 'amor': 41,
 'mío': 42,
 'te': 43,
 'salvas': 44,
 'ahora': 45,
 'corazón': 46,
 'sin': 47,
 'excusas': 48,
 'asisten': 49,
 'me': 50,
 'sigo': 51,
 'pie': 52,
 'a': 53,
 'ese': 54,
 'mar': 55,
 'sacude': 56,
 'oceánicos': 57,
 'nuestros': 58,
 'muertos': 59,
 'quieren': 60,
 'cantemos': 61,
 'los': 62,
 'omisos': 63,
 'vanguardia': 64,
 'todas': 65,
 'mis': 66,
 'intuiciones': 67,
 'asomaron': 68,
 'veces': 69,
 'una': 70,
 'vela': 71,
 'altas': 7

In [79]:
len(indice_palabras)

2858

In [80]:
#convertir datos a enteros porque necesitamos entrenar
train_text_int =[]
test_text_int = []

In [81]:
#acorde a los indices que transformamos construimos el conjunto de entramiento en enteros
for text in train_text:
    tokens = text.split()
    linea_entero = [indice_palabras[token] for token in tokens]
    train_text_int.append(linea_entero)
    

In [82]:
train_text_int

[[1, 2, 3, 4, 5, 6, 7],
 [8, 9, 10, 3, 11, 12, 13],
 [14, 15, 16, 17, 18],
 [19, 20, 5, 21, 22, 23, 24],
 [25],
 [26, 27, 28, 29, 30, 31, 32, 33, 25],
 [34, 3, 35, 36, 37, 38, 39, 40, 41, 42],
 [30, 43, 44, 45],
 [46, 47, 48],
 [2, 49, 30, 50, 49],
 [51, 34, 52],
 [53, 54, 55, 2, 56, 28, 29, 57],
 [30, 58, 59, 60, 2, 61],
 [62, 63, 36, 3, 64],
 [65, 66, 67, 17, 68],
 [53, 69, 70, 71, 72, 72, 73],
 [33, 74],
 [75, 3, 76, 77, 78, 79],
 [80, 22, 81, 33, 82, 34, 83, 84],
 [30, 85, 77, 86, 33, 55],
 [87, 34, 83, 88, 89, 66, 90, 91],
 [92, 93, 34, 37, 94, 95, 77, 83, 96],
 [97, 16, 98],
 [99, 100],
 [101, 77, 102],
 [103, 104, 105, 3, 106],
 [34, 28, 29, 36, 107, 108, 33, 109, 110, 111],
 [112, 22, 62, 113, 17, 114],
 [115, 116, 77, 117],
 [30, 118, 119, 120],
 [47, 121, 30, 122, 123],
 [30, 124, 36, 125],
 [95, 30, 126, 127],
 [128, 129],
 [130, 131, 132, 133, 134],
 [135, 62, 29],
 [30, 37, 136, 137, 138, 36, 139, 36, 140],
 [30, 33, 46, 141],
 [142],
 [143, 144, 36, 145],
 [118, 70, 20, 1

In [83]:
for text in test_text:
    tokens = text.split()
    line_as_int = [indice_palabras.get(token, 0)for token in tokens]
    test_text_int.append(line_as_int)

In [84]:
test_text_int

[[242, 5, 524],
 [34, 252, 17, 2178, 83, 1860, 30, 62, 2179],
 [273, 2182],
 [2765, 34, 3, 2546, 110, 342, 110, 1992],
 [128, 5, 517, 22, 333, 1464],
 [562, 541, 53, 2667],
 [66, 1511, 1256],
 [62, 1510],
 [143, 30, 2849],
 [310, 0],
 [2, 5, 863, 269, 45],
 [728, 3, 1759, 1760, 36, 1018, 30, 1761],
 [254, 2132, 2133, 30, 2134, 2135],
 [2320, 3, 817],
 [5, 1448, 1449, 219, 1450],
 [2712],
 [217, 183, 1546],
 [1063, 242, 1271],
 [488, 30, 5, 17, 2545, 36, 723],
 [50, 1622, 36, 3, 131],
 [1, 2, 3, 4, 5, 6, 7],
 [16, 2344, 273, 1611, 155],
 [2784, 53, 37, 2448, 77, 239, 2785, 1066],
 [2633, 30, 2634],
 [19, 1673],
 [36, 3, 2507, 2508, 30, 36, 62, 2509],
 [242, 2, 333, 18, 242, 2106, 2, 215],
 [2657, 36, 852, 489, 53, 69, 83, 2658],
 [70, 906, 615, 70, 1648, 2220],
 [2678, 2679, 276, 3, 2680, 36, 29],
 [2775, 201, 36, 41],
 [34, 3, 690, 36, 691, 37, 136, 692, 30, 138],
 [827, 36, 2746, 30, 2747, 782],
 [43, 270],
 [194, 672, 815, 2, 357],
 [2162, 913, 36, 1438, 30, 2163, 36, 936],
 [1114, 1

crear matrices de 1

In [85]:
v = len(indice_palabras)
#A va a representar las maatriz de transicion para los textos y pi las probabilidades iniciales de la palabras plicando la MARKOV
A0 = np.ones((v,v))
pi0 = np.ones(v)

A1 = np.ones((v,v))
pi1 = np.ones(v)

In [86]:
A0
#1 para aplicar suavisado +1

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [87]:
pi0

array([1., 1., 1., ..., 1., 1., 1.])

calcular las probabilidades

In [88]:
def compute_counts(text_as_int, A, pi):
    for tokens in text_as_int:
        last_idx  = None
        for idx in tokens:
            #primera palabra de la secuencia
            if last_idx is None:
                pi[idx] +=1
            else:
                A[last_idx, idx] +=1
            last_idx = idx

In [89]:
compute_counts([t for t, y in zip(train_text_int, Ytrain) if y == 0], A0, pi0)
compute_counts([t for t, y in zip(test_text_int, Ytest) if y == 0], A1, pi1)

In [90]:
pi0

array([ 1.,  4., 95., ...,  1.,  1.,  1.])

In [91]:
pi1

array([ 9.,  2., 11., ...,  1.,  1.,  1.])

In [92]:
A0

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 2., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [93]:
A1

array([[7., 1., 3., ..., 1., 1., 1.],
       [1., 1., 2., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

ahora matrices de 0 a 1 para que sean matrices de probabilidad, Normalizando A y pi para que sean matrices de probabilidad validas

In [94]:
A0 /=  A0.sum(axis=1, keepdims=True)
pi0 /= pi0.sum()

A1 /=  A1.sum(axis=1, keepdims=True)
pi1 /= pi1.sum()

In [95]:
pi0

array([0.00018308, 0.00073233, 0.0173929 , ..., 0.00018308, 0.00018308,
       0.00018308])

In [96]:
A0

array([[0.0003499 , 0.0003499 , 0.0003499 , ..., 0.0003499 , 0.0003499 ,
        0.0003499 ],
       [0.00034916, 0.00034916, 0.00069832, ..., 0.00034916, 0.00034916,
        0.00034916],
       [0.00030769, 0.00030769, 0.00030769, ..., 0.00030769, 0.00030769,
        0.00030769],
       ...,
       [0.0003499 , 0.0003499 , 0.0003499 , ..., 0.0003499 , 0.0003499 ,
        0.0003499 ],
       [0.0003499 , 0.0003499 , 0.0003499 , ..., 0.0003499 , 0.0003499 ,
        0.0003499 ],
       [0.0003499 , 0.0003499 , 0.0003499 , ..., 0.0003499 , 0.0003499 ,
        0.0003499 ]])

Vamos a usar el espacio logaritmico ya que los numero son tan chicos

In [97]:
logA0 = np.log(A0)
logpi0 = np.log(pi0)

logA1 = np.log(A1)
logpi1 = np.log(pi1)

In [98]:
logpi0

array([-8.6055703 , -7.21927594, -4.05169341, ..., -8.6055703 ,
       -8.6055703 , -8.6055703 ])

In [99]:
logA0

array([[-7.95787736, -7.95787736, -7.95787736, ..., -7.95787736,
        -7.95787736, -7.95787736],
       [-7.95997453, -7.95997453, -7.26682735, ..., -7.95997453,
        -7.95997453, -7.95997453],
       [-8.08641028, -8.08641028, -8.08641028, ..., -8.08641028,
        -8.08641028, -8.08641028],
       ...,
       [-7.95787736, -7.95787736, -7.95787736, ..., -7.95787736,
        -7.95787736, -7.95787736],
       [-7.95787736, -7.95787736, -7.95787736, ..., -7.95787736,
        -7.95787736, -7.95787736],
       [-7.95787736, -7.95787736, -7.95787736, ..., -7.95787736,
        -7.95787736, -7.95787736]])

In [100]:
#cuenta dde etiquetas de calase 0 en Ytrain
count0 = sum( y == 0 for y in Ytrain)
#cuenta  dde etiquetas de calase 1 en Ytrain
count1 = sum( y == 1 for y in Ytrain)

#cantidad total de ejemplos de entrenamiento
total = len(Ytrain)

#probabilidad a priori de clase 0
p0 = count0 / total
#probabilidad a priori de clase 1
p1 = count1 / total

#logaritmo de la probabilidad a priori de la clase 0
logp0 = np.log(p0)
#logaritmo de la probabilidad a priori de la clase 1
logp1 = np.log(p1)

#ver las probabilidades de ambas clases
p0, p1

(0.7385138967668746, 0.2614861032331254)

The classifier receives three pre-trained probability matrices:

- logAs: Transition probabilities between words (log scale) - "given the previous word was X, what's the probability the next word is Y?"
- logpis: Initial word probabilities (log scale) - "what's the probability a sequence starts with word X?"
- logpriors: Class probabilities (log scale) - "how likely is each class overall?"
- self.K: Number of classes to classify into

Core Calculation (_compute_log_likehood)
This method calculates how likely a text sequence belongs to a specific class:
1. Gets the transition matrix (logA) and initial probabilities (logpi) for the given class
2. Iterates through each word index in the input sequence
3. For the first word: adds logpi[idx] (probability of starting with this word)
4. For subsequent words: adds logA[last_idx, idx] (probability of transitioning from previous word to current word)
Returns the total log probability

Prediction (predict)
1. Calculates posteriors: For each possible class, computes likelihood + prior
2. self._compute_log_likehood(input_, c): How well the sequence fits class c
3. +self.logpriors[c]: Adds the overall probability of class c
4. np.argmax(posteriors): Picks the class with highest probability

In [101]:
#construccion de clasificador 
class Clasifier:
    def __init__(self, logAs, logpis, logpriors):
        self.logAs = logAs
        self.logpis = logpis
        self.logpriors = logpriors
        self.K = len(logpriors) #numero de clases
        
    #funcion de probabilidad de que pertenezca a una clase que se le proporciona
    def _compute_log_likehood(self, input_, class_):
        logA = self.logAs[class_]
        logpi = self.logpis[class_]
            
        last_idx = None
        logprob = 0
        for idx in input_:
            if last_idx is None:
                #es el primer token de la secuencia
                logprob += logpi[idx]
            else:
                #calcula la probabilidad de traansicion de la palabra anterior a la actual
                logprob += logA[last_idx, idx]
                    
            #actualiza las_idx para la proxima iteracion
            last_idx = idx
        return logprob
    
    def predict(self, inputs):
        predictions = np.zeros(len(inputs))
        for i, input_ in enumerate(inputs):
            #calcula los logaritmos de las probabilidades posteriores para cada clase
            posteriors = [self._compute_log_likehood(input_, c) + self.logpriors[c]  
                          for c in range(self.K)]
            
            pred = np.argmax(posteriors)
            predictions[i] = pred
        return predictions
    

#cada arreglo debe esstar en orden ya que se asume que las clases indexan estas listas

In [102]:
clf = Clasifier([logA0, logA1], [logpi0, logpi1], [logp0, logp1])

In [103]:
Ptrain = clf.predict(train_text_int)
print(f"Train accuracy: {np.mean(Ptrain == Ytrain)}")

Train accuracy: 0.7385138967668746


In [104]:
Ptest = clf.predict(test_text_int)
print(f"Test accuracy: {np.mean(Ptest == Ytest)}")

Test accuracy: 0.7142857142857143
