In [47]:
import numpy as np
import matplotlib.pyplot as plt
import string
from sklearn.model_selection import train_test_split

In [48]:
archivos = [
    "benedetti.txt",
    "neruda.txt"
]

In [49]:
texts = []
labels = []

In [50]:
for label, l in enumerate(archivos):
    print(f"{l} Corresponde a {label}")
    
    with open(l, "r", encoding="utf-8") as archivo:
        for line in archivo: #recorrer cada una de las lineas de los textos con line
            #print(line)
            line = line.rstrip().lower() #todo a minuscula
            #print(line)
            if line:
                #eliminar puntuacion
                line = line.translate(str.maketrans("", "", string.punctuation))
                texts.append(line)
                labels.append(label)
            print(line)
            

benedetti.txt Corresponde a 0
poemas varios
mario benedetti

la buena tiniebla
una mujer desnuda y en lo oscuro
genera un resplandor que da confianza
de modo que si sobreviene
un apagón o un desconsuelo
es conveniente y hasta imprescindible
tener a mano una mujer desnuda
entonces las paredes se acuarelan
el cielo raso se convierte en cielo
las telarañas vibran en su ángulo
los almanaques dominguean
y los ojos felices y felinos
miran y no se cansan de mirar
una mujer desnuda y en lo oscuro
una mujer querida o a querer
exorcisa por una vez la muerte

preliminar del miedo
por sobre las terrazas alunadas
donde se aman cautelosamente los gatos
y los brillos esquivan las chimeneas
creo que nadie sabe lo que yo sé esta noche
algo aprendido a pedacitos y a pulsaciones
y que integra mi pánico tradicional modesto
¿cómo desmenuzar plácidamente el miedo
comprender por fin que no es una excusa
sino un escalofrío parecido al disfrute
sólo que amarguísimo y si atenuantes
los suicidas no tienen proble

In [51]:
texts

['poemas varios',
 'mario benedetti',
 'la buena tiniebla',
 'una mujer desnuda y en lo oscuro',
 'genera un resplandor que da confianza',
 'de modo que si sobreviene',
 'un apagón o un desconsuelo',
 'es conveniente y hasta imprescindible',
 'tener a mano una mujer desnuda',
 'entonces las paredes se acuarelan',
 'el cielo raso se convierte en cielo',
 'las telarañas vibran en su ángulo',
 'los almanaques dominguean',
 'y los ojos felices y felinos',
 'miran y no se cansan de mirar',
 'una mujer desnuda y en lo oscuro',
 'una mujer querida o a querer',
 'exorcisa por una vez la muerte',
 'preliminar del miedo',
 'por sobre las terrazas alunadas',
 'donde se aman cautelosamente los gatos',
 'y los brillos esquivan las chimeneas',
 'creo que nadie sabe lo que yo sé esta noche',
 'algo aprendido a pedacitos y a pulsaciones',
 'y que integra mi pánico tradicional modesto',
 '¿cómo desmenuzar plácidamente el miedo',
 'comprender por fin que no es una excusa',
 'sino un escalofrío parecido 

In [52]:
print(labels)

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 

In [53]:
train_text, test_text, Ytrain, Ytest = train_test_split(texts, labels, test_size=0.1, random_state=42)

In [54]:
len(Ytrain), len(Ytest)

(1761, 196)

In [55]:
test_text

['diptongos como caracoles',
 'y tiritan azules los astros a lo lejos',
 'pero tú clara niña pregunta de humo espiga',
 'emerges de las cosas llena del alma mía',
 'alejarme del odio',
 'lunar solar ardiente y frío repentino',
 'reconoce en los míos',
 'y claro allí inventaba árboles rojos',
 'de los males endémicos y de los académicos',
 'no sé cómo ni sé',
 'que le quede bien claro',
 'o sea',
 'un derrumbe de algún modo no previsto',
 'tan desolada',
 'al menos no lo sabe en esta espera',
 'a mi alma sola y salvaje a mi nombre que todos ahuyentan',
 'se debe a que hice muchos borradores',
 'nostalgia',
 'estoy',
 'usted preguntará por que cantamos',
 'y eso en verdad no es nada extraordinario',
 'estoy en mi ventana',
 'y por cierto me vieron',
 'no te salves ahora',
 'llora limpio de culpas',
 'y hostil',
 'sigo en pie',
 'no sé si de reojo o de hito en hito',
 'de fatigados duendes que ya no ocurren',
 'hacerlo trizas con la mirada',
 'incendio en el bosque arde en cruces azules',

In [56]:
#<unk> es una convencion que se utiliza a menudo en NLP para representar
#palabras desconocidas o fuera del vocabulario. En este caso, se esta
#asignando el indice 0 a esta palabra especial
indice = 1
indice_palabras = {"<unk>": 0}

In [59]:
#construccion deun diccionario de codificacion de palabras a indices
#recorrer el conjunto de entranmiento # a cada linea se le asigna una tokenizacion, es decir separar en palabras las lineas
#y a cada palabra se le asigna un indice
for text in train_text:  
    tokens = text.split()  
    for token in tokens: 
        if token not in indice_palabras:
            indice_palabras[token] = indice  
            indice += 1

In [60]:
indice_palabras

{'<unk>': 0,
 'algo': 1,
 'con': 2,
 'alas': 3,
 'de': 4,
 'pájaro': 5,
 'angustia': 6,
 'y': 7,
 'olvido': 8,
 'inmóvil': 9,
 'paciente': 10,
 'en': 11,
 'ti': 12,
 'se': 13,
 'acumularon': 14,
 'las': 15,
 'guerras': 16,
 'los': 17,
 'vuelos': 18,
 'da': 19,
 'soledades': 20,
 'la': 21,
 'lluvia': 22,
 'el': 23,
 'llanto': 24,
 'por': 25,
 'eso': 26,
 'me': 27,
 'defienden': 28,
 'pálida': 29,
 'cuando': 30,
 'desaman': 31,
 'cuadros': 32,
 'andan': 33,
 'días': 34,
 'iguales': 35,
 'persiguiéndose': 36,
 'oh': 37,
 'boca': 38,
 'mordida': 39,
 'besados': 40,
 'miembros': 41,
 'llegan': 42,
 'van': 43,
 'sólo': 44,
 'un': 45,
 'rincón': 46,
 'tranquilo': 47,
 'esos': 48,
 'que': 49,
 'vos': 50,
 'mirás': 51,
 'como': 52,
 'siempre': 53,
 'no': 54,
 'sé': 55,
 'cómo': 56,
 'ni': 57,
 'siquiera': 58,
 'una': 59,
 'hebilla': 60,
 'o': 61,
 'manga': 62,
 '¿te': 63,
 'importa': 64,
 'nebulosa': 65,
 'te': 66,
 'dibuje': 67,
 'destino': 68,
 'provocaciones': 69,
 'xiv': 70,
 'otros': 71,
 

In [61]:
len(indice_palabras)

2669

In [62]:
#convertir datos a enteros porque necesitamos entrenar
train_text_int =[]
test_text_int = []

In [65]:
#acorde a los indices que transformamos construimos el conjunto de entramiento en enteros
for text in train_text:
    tokens = text.split()
    linea_entero = [indice_palabras[token] for token in tokens]
    train_text_int.append(linea_entero)
    

In [66]:
train_text_int

[[1, 2, 3, 4, 5, 1, 4, 6, 7, 4, 8],
 [9, 7, 10],
 [11, 12, 13, 14, 15, 16, 7, 17, 18],
 [19],
 [20],
 [21, 22, 2, 23, 24],
 [25, 26],
 [27, 28, 4, 21, 29],
 [7, 30, 13, 31],
 [17, 32],
 [33, 34, 35, 36],
 [37, 21, 38, 39, 37, 17, 40, 41],
 [42, 7, 13, 43],
 [44, 45, 46, 47],
 [4, 48, 49, 50, 51],
 [52, 53],
 [54, 55, 56, 57, 55],
 [57, 58, 59, 60, 61, 59, 62],
 [63, 64, 49, 59, 65, 66, 67, 23, 68],
 [69],
 [70],
 [17, 71, 49, 72, 73, 74, 75, 76, 49, 77, 54, 27],
 [56, 66, 78, 79, 80, 81, 82],
 [83, 84, 85],
 [21, 86, 87, 49, 88, 21, 89],
 [90],
 [4, 15, 91, 92, 7, 4, 17, 93],
 [94, 95, 7, 2, 96, 4, 97],
 [98, 99, 100, 101, 102, 88, 23, 103],
 [104, 21, 105],
 [106],
 [107, 54, 108, 109],
 [21, 89, 88, 110, 111, 49, 45, 112, 113],
 [114, 115, 116, 7, 80, 116],
 [7, 45, 117, 13, 118, 100, 119, 11, 120],
 [121, 122, 21, 4, 123],
 [124, 125],
 [7, 126, 127, 7, 128, 73, 52, 129, 17, 130],
 [131, 132, 133, 66, 130],
 [134],
 [49, 135, 136, 7, 137],
 [17, 138, 4, 21, 139],
 [49, 54, 13, 140, 

In [67]:
for text in test_text:
    tokens = text.split()
    line_as_int = [indice_palabras.get(token, 0)for token in tokens]
    test_text_int.append(line_as_int)

In [69]:
test_text_int

[[0, 52, 437],
 [7, 0, 1713, 17, 0, 100, 260, 381],
 [227, 287, 0, 1839, 2164, 4, 253, 2167],
 [0, 4, 15, 756, 1472, 197, 302, 79],
 [0, 197, 0],
 [0, 0, 0, 7, 1082, 0],
 [863, 11, 17, 0],
 [7, 805, 1153, 0, 680, 0],
 [4, 17, 0, 0, 7, 4, 17, 0],
 [54, 55, 56, 57, 55],
 [49, 329, 1994, 750, 805],
 [61, 1225],
 [45, 0, 4, 564, 596, 54, 0],
 [146, 0],
 [229, 1299, 54, 260, 510, 11, 148, 1460],
 [100, 165, 302, 190, 7, 2366, 100, 165, 251, 49, 246, 0],
 [13, 0, 100, 49, 1217, 0, 0],
 [269],
 [195],
 [237, 1670, 25, 49, 861],
 [7, 26, 11, 1222, 54, 88, 110, 0],
 [195, 11, 165, 692],
 [7, 25, 836, 27, 0],
 [54, 66, 2285, 377],
 [0, 0, 4, 2529],
 [7, 0],
 [504, 11, 505],
 [54, 55, 273, 4, 0, 61, 4, 0, 11, 0],
 [4, 0, 0, 49, 357, 54, 0],
 [0, 0, 2, 21, 727],
 [1025, 11, 23, 1426, 1775, 11, 706, 1713],
 [80, 209, 0, 75, 12, 0],
 [232, 197, 0, 7, 4, 15, 0],
 [52, 13, 510, 11, 0, 0, 88, 0],
 [488, 1258, 1047, 0, 23, 117],
 [0, 488, 0, 260, 49, 491, 2, 406, 738, 52, 0, 260, 49, 329, 2191],
 [111, 

crear matrices de 1

In [76]:
v = len(indice_palabras)
#A va a representar las maatriz de transicion para los textos y pi las probabilidades iniciales de la palabras plicando la MARKOV
A0 = np.ones((v,v))
pi0 = np.ones(v)

A1 = np.ones((v,v))
pi1 = np.ones(v)

In [77]:
A0
#1 para aplicar suavisado +1

array([[1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       ...,
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.],
       [1., 1., 1., ..., 1., 1., 1.]])

In [78]:
pi0

array([1., 1., 1., ..., 1., 1., 1.])

calcular las probabilidades

In [83]:
def compute_counts(text_as_int, A, pi):
    for tokens in text_as_int:
        last_idx  = None
        for idx in tokens:
            #primera palabra de la secuencia
            if last_idx is None:
                pi[idx] +=1
            else:
                A[last_idx, idx] +=1
            last_idx = idx

In [86]:
compute_counts([t for t, y in zip(train_text_int, Ytrain) if y == 0], A0, pi0)
compute_counts([t for t, y in zip(test_text_int, Ytest) if y == 0], A1, pi1)

In [87]:
pi0

array([21.,  2., 45., ...,  1.,  1.,  1.])

In [88]:
pi1

array([21.,  2.,  1., ...,  1.,  1.,  1.])

In [89]:
A0

array([[25.,  1.,  3., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 2.,  1.,  1., ...,  1.,  1.,  1.],
       ...,
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.]])

In [90]:
A1

array([[25.,  1.,  3., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 2.,  1.,  1., ...,  1.,  1.,  1.],
       ...,
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.],
       [ 1.,  1.,  1., ...,  1.,  1.,  1.]])